### ISSUE TITLE
Site is not updated

### ISSUE THREAD

**Issue by kwkwan** [paneron/paneron.github.io#2]
The cron job defined in yaml file does not work as expected.

**Comment by strogonoff** [comment]
@CAMOBAP could you take a look? It looks like the site was updated 2 months ago last: https://github.com/paneron/paneron.org/actions

**Comment by CAMOBAP** [comment]
<img width="1280" alt="Screenshot 2023-08-15 at 1 40 14 PM" src="https://github.com/paneron/paneron.org/assets/2169738/ab078318-86a2-410a-9544-01d341271038">

I will add `keep-alive` workflow

**Comment by CAMOBAP** [comment]
executed manually this time , bu later cron will works properly

**Comment by strogonoff** [comment]
@CAMOBAP wrote elsewhere:

> Recap previous releases:
> - 2.1.4 - not updated because windows failed https://github.com/paneron/paneron/actions/runs/5782392990
> - 2.1.3 - not updated because credentials issue  https://github.com/paneron/paneron/actions/runs/5656237863/job/15323450531

> @strogonoff can you confirm that `secrets.GH_PANERON_CI_TOKEN` exists and up to date?

Do you mean secrets in this repository’s settings? I can’t, but maybe @ribose-jeffreylau can.

**Comment by ronaldtse** [comment]
@CAMOBAP the token exists.

<img width="787" alt="Screenshot 2023-08-18 at 2 01 06 PM" src="https://github.com/paneron/paneron.org/assets/11865/88cf8cf2-940d-4b44-afd3-96f802a82243">

**Comment by strogonoff** [comment]
It looks like `keep-alive` is not working? Last time was last month, but there were releases since then and site was not rebuilt.

<img width="1067" alt="Screenshot 2023-09-28 at 13 11 50" src="https://github.com/paneron/paneron.org/assets/292959/d2728c1d-7a5b-4c45-9d53-31677b447141">

**Comment by CAMOBAP** [comment]
@strogonoff `keep-alive` looks working (it runs once a 50 days) but there definitely issue with `deploy-master`. According to cron `42 */12 * * *` it should run ~ "every 12th hour" but it doesn't happens and it doesn't look disabled on UI

Per API it is "active" also 

> curl -H "Authorization: token XXX" "https://api.github.com/repos/paneron/paneron.org/actions/workflows/deploy-master.yml"

```
{
  "id": 14215863,
  "node_id": "W_kwDOEfhz7M4A2Oq3",
  "name": "deploy-master",
  "path": ".github/workflows/deploy-master.yml",
  "state": "active",
  "created_at": "2021-10-15T13:18:50.000+02:00",
  "updated_at": "2023-08-15T13:42:57.000+02:00",
  "url": "https://api.github.com/repos/paneron/paneron.org/actions/workflows/14215863",
  "html_url": "https://github.com/paneron/paneron.org/blob/master/.github/workflows/deploy-master.yml",
  "badge_url": "https://github.com/paneron/paneron.org/workflows/deploy-master/badge.svg"
}
```

I see that some code in `.github/workflows/deploy-master.yml` is outdated, let me update it and see will it trigger next scheduled run

**Comment by CAMOBAP** [comment]
@strogonoff @kwkwan please review https://github.com/paneron/paneron.org/pull/3

Once it merged let's wait for 12h and see will the workflow triggered or not, if not I will proceed with investigation further

**Comment by CAMOBAP** [comment]
Scheduling now works, but it still strange why it doesn't work, probably GitHub Actions have another undocumented checks

I will continue research to implement it properly

**Comment by CAMOBAP** [comment]
cron expression fixed
